# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ml',
                'doc_host': 'https://DiTscho.github.io',
                'git_url': 'https://github.com/DiTscho/ml',
                'lib_path': 'ml'},
  'syms': { 'ml.nb_00_preprocessing': { 'ml.nb_00_preprocessing._get_files': ('preprocessing.html#_get_files', 'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing._get_tma_id': ( 'preprocessing.html#_get_tma_id',
                                                                                'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing._get_tma_spot': ( 'preprocessing.html#_get_tma_spot',
                                                                                  'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing.get_clinical_data': ( 'preprocessing.html#get_clinical_data',
                                                                                      'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing.get_files': ('preprocessing.html#get_files', 'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing.get_tma_id': ('preprocessing.html#get_tma_id', 'ml/nb_00_preprocessing.py'),
                                        'ml.nb_00_preprocessing.get_tma_spot': ( 'preprocessing.html#get_tma_spot',
                                                                                 'ml/nb_00_preprocessing.py')}}}