# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ml',
                'doc_host': 'https://DiTscho.github.io',
                'git_url': 'https://github.com/DiTscho/ml',
                'lib_path': 'ml'},
  'syms': {'ml.core': {'ml.core.foo': ('core.html#foo', 'ml/core.py')}}}