# AUTOGENERATED! DO NOT EDIT! File to edit: ../04b_dataset_more_abstract.ipynb.

# %% auto 0
__all__ = ['open_image']

# %% ../04b_dataset_more_abstract.ipynb 2
from fastai.data.transforms import get_image_files

# %% ../04b_dataset_more_abstract.ipynb 5
import PIL

# %% ../04b_dataset_more_abstract.ipynb 8
import torch
import numpy as np

# %% ../04b_dataset_more_abstract.ipynb 9
def open_image(fname, size=256):
    img = PIL.Image.open(fname).convert('RGB')
    img = img.resize((size,size))
    t = torch.Tensor(np.array(img))
    return t.permute(2,0,1).float()/255.0
