# AUTOGENERATED! DO NOT EDIT! File to edit: ../03a_testing_fastai.ipynb.

# %% auto 0
__all__ = ['p_outx', 'p_outy']

# %% ../03a_testing_fastai.ipynb 2
from pathlib import Path 

#|export
import pandas as pd

#| export
import matplotlib.pyplot as plt

#|export
from .nb_02_patching import *

# %% ../03a_testing_fastai.ipynb 3
from .nb_03_dataset import *

# %% ../03a_testing_fastai.ipynb 4
p_outx = Path("/media/dimi/TOSHIBA EXT/patched_images")
p_outy = Path("/media/dimi/TOSHIBA EXT/patched_masks")
